//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Framework.VerifyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VerifyServiceReference.IVerifyService")]
    public interface IVerifyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifyService/VerifyUserLdap", ReplyAction="http://tempuri.org/IVerifyService/VerifyUserLdapResponse")]
        string VerifyUserLdap(string userName, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerifyService/VerifyUserLdap", ReplyAction="http://tempuri.org/IVerifyService/VerifyUserLdapResponse")]
        System.Threading.Tasks.Task<string> VerifyUserLdapAsync(string userName, string userPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerifyServiceChannel : Module.Framework.VerifyServiceReference.IVerifyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyServiceClient : System.ServiceModel.ClientBase<Module.Framework.VerifyServiceReference.IVerifyService>, Module.Framework.VerifyServiceReference.IVerifyService {
        
        public VerifyServiceClient() {
        }
        
        public VerifyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifyUserLdap(string userName, string userPassword) {
            return base.Channel.VerifyUserLdap(userName, userPassword);
        }
        
        public System.Threading.Tasks.Task<string> VerifyUserLdapAsync(string userName, string userPassword) {
            return base.Channel.VerifyUserLdapAsync(userName, userPassword);
        }
    }
}
